---
version: "3"
services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl:/etc/letsencrypt:ro
      - dh:/etc/nginx/dhparam.pem:ro
      - challenge:/var/ww3/certbot/:ro
      - ./www:/var/www:ro
#      - ./conf/nginx/nginx_no_ssl.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
  ssl:
    image: certbot/certbot:latest
    volumes:
      - ssl:/etc/letsencrypt/:rw
      - challenge:/var/www/certbot:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email kikefontanlorenzo@gmail.com -d kike.wtf -d www.kike.wtf --agree-tos
    depends_on: webserver
  dh:
    image: alpine/openssl:latest
    volumes:
      - dh:/dhparam.pem:rw
    command: openssl dhparam -out /dhparam.pem 4096
    depends_on: webserver
volumes:
  dh:
  ssl:
  challenge:

