---
version: "3.7"
services:
  kike.wtf:
    container_name: kike.wtf
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.kike.entrypoints=https
      - traefik.http.routers.kike.tls.certresolver=ssl
      - traefik.http.routers.kike.rule=Host(`kike.wtf`)
    volumes:
      - ./www/kike.wtf:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on: ["reverse-proxy"]

  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:latest
    command:
      --log.level=INFO
      --providers.docker
      --providers.docker.exposedbydefault=false
      --entrypoints.http.address=":80"
      --entrypoints.https.address=":443"
      --entrypoints.http.redirections.entrypoint.to=https
      --entrypoints.http.redirections.entrypoint.scheme=https
      --certificatesresolvers.ssl.acme.email=hello@kike.wtf
      --certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json
      --certificatesresolvers.ssl.acme.httpchallenge
      --certificatesresolvers.ssl.acme.httpchallenge.entrypoint=http
      --global.sendanonymoususage=false
    ports: ["80:80","443:443"]
    volumes:
      - certs:/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  certs: