---
version: "3.5"
services:
  kike.wtf:
    container_name: kike.wtf
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=kike.wtf,ww3.kike.wtf
      - LETSENCRYPT_HOST=kike.wtf,ww3.kike.wtf
    restart: unless-stopped
    depends_on: ["proxy","proxy-gen","ssl"]

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports: ["80:80","443:443"]
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d:ro
      - html:/usr/share/nginx/html:ro
      - vhost:/etc/nginx/vhost.d:ro
    restart: unless-stopped

  proxy-gen:
    container_name: proxy-gen
    image: nginxproxy/docker-gen:latest
    volumes:
      - conf:/etc/nginx/conf.d:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/templates:/etc/docker-gen/templates:ro
    restart: unless-stopped
    command: -notify-sighup proxy -watch -only-published -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on: ["proxy"]

  ssl:
    container_name: ssl
    image: nginxproxy/acme-companion:latest
    environment:
      - DEFAULT_EMAIL=hello@kike.wtf
      - NGINX_PROXY_CONTAINER=proxy
      - NGINX_DOCKER_GEN_CONTAINER=proxy-gen
    volumes:
      - acme:/etc/acme.sh:rw
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html:rw
      - vhost:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on: ["proxy-gen"]

volumes:
  acme:
  certs:
  conf:
  html:
  vhost: