---
version: "3.7"
services:
  kike.wtf:
    container_name: kike.wtf
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.kike.rule=Host(`kike.wtf`,`www.kike.wtf`)
      - traefik.http.routers.kike.entrypoints=websecure
      - traefik.http.routers.kike.tls=true
      - traefik.http.routers.kike.tls.certresolver=ssl
      - traefik.http.routers.kike.middlewares=security-headers@file,compression@file
    volumes:
      - ./www/kike.wtf:/usr/share/nginx/html:ro
      - ./config/nginx/kike.wtf.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on: ["reverse-proxy"]

  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:latest
    volumes:
      - certs:/letsencrypt:rw
      - ./config/traefik:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: ["80:80","443:443"]
    restart: unless-stopped

volumes:
  certs: