---
log:
  level: INFO

global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  file:
    directory: /etc/traefik/config
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websercure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  ssl:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entrypoint: web